return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "stylua",
      "shfmt",
      "black",
      "clangd",
      "codelldb",
      "css-lsp",
      "gofumpt",
      "goimports",
      "gopls",
      "html-lsp",
      "json-lsp",
      "lua-language-server",
      "marksman",
      "prettier",
      "prettierd",
      "pyright",
      "ruff-lsp",
      "rust-analyzer",
      "tailwindcss-language-server",
      "taplo",
      "typescript-language-server",
      "yaml-language-server",
    },
  },
}
